### ISSUE TITLE
Doesn't do anything for me

### ISSUE THREAD

**Issue by FutRR** [Tomasak/GTA-Downgraders#3] opened 2024-08-31 00:45 UTC
As the title says the mod just doesn't work for me, I chose the pre-cut songs and nothing else, I already have FusionFix installed but the mod doesn't apply it seems.
I don't have any of the "new" songs and I still get some eurodance but a tad less (might be random)

Is there any way to remove the specific mod files from the main folder so that I can re-install it safely?
Or maybe the mod needs a new game? I'm new to GTAIV modding so aside from a few reddit post and yt videos idk what could cause that

**Comment by 2Col** [comment] 2024-08-31 06:24
Also it seems that with IV-RR-24-08-2024 split radio option doesn't work. I still get EFLC songs in IV's Radio Vladivostok and vice versa.

Meanwhile you could try previous version of this mod
https://github.com/Tomasak/GTA-Downgraders/releases/tag/IV-old

**Comment by Tomasak** [comment] 2024-08-31 07:34
What version do you have? Steam or RGL? There might be some issues with installer :/

**Comment by 2Col** [comment] 2024-08-31 07:43
Steam

**Comment by FutRR** [comment] 2024-08-31 08:05
Steam too

**Comment by Tomasak** [comment] 2024-08-31 08:10
[test exe.zip](https://github.com/user-attachments/files/16823913/test.exe.zip)
please test this exe, extract it to your existing Radio Restoration installer. There were several typos, but they should be gone now :)

**Comment by 2Col** [comment] 2024-08-31 09:54
I only tested IV with Pre-cut songs + Split radios options and everything seems to be working as intended.

EDIT: TBOGT works fine too.

**Comment by 2Col** [comment] 2024-08-31 11:00
Also, could you fix Radio Restorer in IVFixer? It has same issues mentioned here.

**Comment by FutRR** [comment] 2024-08-31 11:19
> [test exe.zip](https://github.com/user-attachments/files/16823913/test.exe.zip)
> 
> please test this exe, extract it to your existing Radio Restoration installer. There were several typos, but they should be gone now :) 

I won't be able to try this weekend but I'll let you know on monday, thanks in advance!

**Comment by Tomasak** [comment] 2024-08-31 11:48
> Also, could you fix Radio Restorer in IVFixer? It has same issues mentioned here.

redirected to icrym.



> > [test exe.zip](https://github.com/user-attachments/files/16823913/test.exe.zip)
> > please test this exe, extract it to your existing Radio Restoration installer. There were several typos, but they should be gone now :)
> 
> I won't be able to try this weekend but I'll let you know on monday, thanks in advance!

you can try the latest release just in case (if you dont have some kind of limited downloads)

**Comment by ICantReadYourMind** [comment] 2024-08-31 13:07
> Also, could you fix Radio Restorer in IVFixer? It has same issues mentioned here.

rather simple fix, just have to add -y to end of all 7z commands. i will push new update soon

**Comment by FutRR** [comment] 2024-09-01 10:37
> you can try the latest release just in case (if you dont have some kind of limited downloads)

I managed to test it this morning but only had EDM songs again, I only picked pre-cut songs.

Maybe it would work better with a "manual" installation (update folder) though keep in mind that I don't know shit about GTAIV modding lol so it's just a suggestion

**Comment by Tomasak** [comment] 2024-09-01 10:39
can you send picture of your update folder?
or if you dont want to have eurodance vladivostok in base IV, you have to install split radio option. So eurodance is tbogt/tlad only (like eflc) and IV has only russian vladivostok songs.

**Comment by FutRR** [comment] 2024-09-01 14:59
alright I'll try that tonight when I get back

**Comment by FutRR** [comment] 2024-09-03 17:20
> can you send picture of your update folder?
> 
> or if you dont want to have eurodance vladivostok in base IV, you have to install split radio option. So eurodance is tbogt/tlad only (like eflc) and IV has only russian vladivostok songs.

Sorry I totally forgot to reply yesterday, I installed it with the split radio option and it works fine! haven't played episodes yet though since it's my 1st playthrough, I'll let you know if it doesn't work

**Comment by Tomasak** [comment] 2024-09-03 17:42
tbh if it works in iv, it must work also in episodes, so im closing this, if there is more problems either comment here or open new issue :)

**Closed as completed by Tomasak** 2024-09-03 17:42 UTC
